name: Matrix Demo
on: push
jobs:
  build: 
    strategy: 
      matrix: 
        node-version: [12,14,20]
        OS: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.OS}}
    steps: 
      - name: get code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with: 
          node_version: ${{matrix.node-version}}
      - name: install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build  